### ISSUE TITLE
Adopt stringables run error

### ISSUE THREAD

**Issue by driftingly** [laravel-shift/workbench-issues#74]
**Desktop:**
 - OS: Mac
 - OS Version: macOS Monterey 12.2.1
 - App Version: 0.8.3

**Describe the bug**
Ran into the below error message when running Adopt stringables with the Use Helper option enabled.

**To Reproduce**
Run the Adopt stringables shift.

**Error**
```
Warning: Undefined array key 0 in phar:///opt/shift/workbench/src/Parsers/Finders/StrFinder.php on line 88

Warning: Attempt to read property "value" on null in phar:///opt/shift/workbench/src/Parsers/Finders/StrFinder.php on line 88

Fatal error: Uncaught Error: Call to a member function getAttribute() on null in phar:///opt/shift/workbench/src/Parsers/Finders/StrFinder.php:88
Stack trace:
#0 phar:///opt/shift/workbench/src/Parsers/Finders/StrFinder.php(41): Shift\Parsers\Finders\StrFinder->extractSubject(Object(PhpParser\Node\Expr\StaticCall))
#1 phar:///opt/shift/workbench/src/Parsers/NikicParser.php(39): Shift\Parsers\Finders\StrFinder->process(Array)
#2 phar:///opt/shift/workbench/src/Tasks/Workbench/AdoptStringable.php(38): Shift\Parsers\NikicParser->parse('<?php\n\nnamespac...')
#3 phar:///opt/shift/workbench/workbench.php(89): Shift\Tasks\Workbench\AdoptStringable->perform()
#4 /opt/shift/workbench(9): require('phar:///opt/shi...')
#5 {main}
  thrown in phar:///opt/shift/workbench/src/Parsers/Finders/StrFinder.php on line 88
```

**Comment by driftingly** [comment]
The issue might be due to a string macro: `Str::macro('possessive', function ($str) {});`

**Comment by jasonmccreary** [comment]
It's possible. I'll add a `macro` call to our test cases and see what happens.

**Comment by driftingly** [comment]
I removed the macro and tried again and still ran into the error, so it doesn't appear to be the issue.
