### ISSUE TITLE
Class not found in "Class based factories" Task

### ISSUE THREAD

**Issue by tobz-nz** [laravel-shift/workbench-issues#8]
**Desktop:**
 - OS: Mac
 - OS Version: Big Sur
 - App Version: 0.2.3

**Describe the bug**
Error when running the "Class based factories" task

```
Analyzing project...

Fatal error: Uncaught Error: Class "Shift\Tasks\Laravel\Eight\Factories" not found in phar:///opt/shift/workbench/src/Tasks/Workbench/ClassBasedFactories.php:10
Stack trace:
#0 phar:///opt/shift/workbench/vendor/composer/ClassLoader.php(480): include()
#1 phar:///opt/shift/workbench/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('phar:///opt/shi...')
#2 phar:///opt/shift/workbench/src/Factories/TaskFactory.php(93): Composer\Autoload\ClassLoader->loadClass('Shift\\Tasks\\Wor...')
#3 phar:///opt/shift/workbench/src/Shifts/Laravel/WorkbenchBuild.php(40): Shift\Factories\TaskFactory::createTaskFromUses(Array)
#4 [internal function]: Shift\Shifts\Laravel\WorkbenchBuild->Shift\Shifts\Laravel\{closure}(Array, 0)
#5 phar:///opt/shift/workbench/vendor/illuminate/collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#6 phar:///opt/shift/workbench/src/Shifts/Laravel/WorkbenchBuild.php(41): Illuminate\Support\Collection->map(Object(Closure))
#7 [internal function]: Shift\Shifts\Laravel\WorkbenchBuild->Shift\Shifts\Laravel\{closure}(Object(Illuminate\Support\Collection), 'laravel/class-b...')
#8 phar:///opt/shift/workbench/vendor/illuminate/collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#9 phar:///opt/shift/workbench/src/Shifts/Laravel/WorkbenchBuild.php(42): Illuminate\Support\Collection->map(Object(Closure))
#10 phar:///opt/shift/workbench/workbench.php(57): Shift\Shifts\Laravel\WorkbenchBuild->__construct(Array)
#11 /opt/shift/workbench(9): require('phar:///opt/shi...')
#12 {main}
  thrown in phar:///opt/shift/workbench/src/Tasks/Workbench/ClassBasedFactories.php on line 10

```

**To Reproduce**
Run the task.

**Comment by jasonmccreary** [comment]
@tobz-nz, thanks for reporting. We'll get a new build pushed later today to get this fixed.

**Comment by jasonmccreary** [comment]
@tobz-nz, just pushed release 0.2.4 which should resolve this issue. Of course let us know if not.
