### ISSUE TITLE
Streamline Tailwind Config task is throwing an exception

### ISSUE THREAD

**Issue by Jamesking56** [laravel-shift/workbench-issues#87]
**Desktop:**
 - OS: Mac
 - OS Version: Monterey 12.6
 - App Version: 1.0.3

**Describe the bug**
Streamline Tailwind config task is broken and crashes:

```
Running: tailwind/streamline-config

Warning: file_get_contents(/opt/shift/resources/stubs/default.config.9.x.js): Failed to open stream: No such file or directory in phar:///opt/shift/workbench/src/Helpers/UtilityHelper.php on line 1661

Fatal error: Uncaught TypeError: Shift\Models\TailwindConfig::__construct(): Argument #1 ($config) must be of type array, null given, called in phar:///opt/shift/workbench/src/Models/TailwindConfig.php on line 118 and defined in phar:///opt/shift/workbench/src/Models/TailwindConfig.php:15
Stack trace:
#0 phar:///opt/shift/workbench/src/Models/TailwindConfig.php(118): Shift\Models\TailwindConfig->__construct(NULL, '')
#1 phar:///opt/shift/workbench/src/Tasks/Tailwind/StreamlineConfig.php(30): Shift\Models\TailwindConfig::parse('', '9.x')
#2 phar:///opt/shift/workbench/workbench.php(91): Shift\Tasks\Tailwind\StreamlineConfig->perform()
#3 /opt/shift/workbench(9): require('phar:///opt/shi...')
#4 {main}
  thrown in phar:///opt/shift/workbench/src/Models/TailwindConfig.php on line 15
```

**To Reproduce**
Run the tailwind streamline config task, I think its a problem with the Docker image rather than any specific OS.

**Comment by jasonmccreary** [comment]
Thanks for reporting. I'll try to get this cleaned up next week.
